#!/bin/bash

die () {
    echo "$*"
    exit 1
}

XCL="/producers"
XCL+="|package-info"
XCL+="|/kythe"
XCL+="|/kotlin"
XCL+="|/Producer"
XCL+="|/Produces"
XCL+="|/Production"
XCL+="|/JavacPlugin"
XCL+="|/TypeNames"
XCL+="|/JavacPlugin"
XCL+="|/ProvisionDependencyOnProducerBinding"
XCL+="|/DependsOnProduction"
XCL+="|/MonitoringModule"
XCL+="|/ExternalBindingGraphConverter"
XCL+="|Hjar"
XCL+="|/ImmediateFuture"
XCL+="|/DependencyMethodProducer"
XCL+="|/ServiceLoaders"
#XCL+="|"

echo $XCL
for S in `find ../dagger/java/dagger/internal/codegen/ -name "*.java" | grep -v -E "$XCL"`; do
  ./fetch internal `basename $S`
done

