#!/bin/bash

die () {
    echo "$*"
    exit 1
}

XCL="/producers"
XCL+="|package-info"
XCL+="|/kythe"
XCL+="|/kotlin"
XCL+="|/testing"
XCL+="|/Producer"
XCL+="|/Produces"
XCL+="|/Production"
XCL+="|/JavacPlugin"
XCL+="|/TypeNames"
XCL+="|/JavacPlugin"
XCL+="|/ProvisionDependencyOnProducerBinding"
XCL+="|/DependsOnProduction"
XCL+="|/MonitoringModule"
XCL+="|/ExternalBindingGraphConverter"
XCL+="|Hjar"
XCL+="|/ImmediateFuture"
XCL+="|/DependencyMethodProducer"
XCL+="|/ServiceLoaders"
XCL+="|/codegen/base/Util"
XCL+="|/SourceFileGenerator"
XCL+="|/DaggerStreams"
#XCL+="|"

if [[ "internal" == "$1" ]]; then
  INTERNAL=1
  shift
elif [[ "spi" == "$1" ]]; then
  SPI=1
  shift
fi

if [[ -n $SPI ]]; then
  for S in `find ../dagger/java/dagger/spi/ -name "*.java" | grep -v -E "$XCL"`; do
    ./fetch spi `basename $S`
  done
elif [[ -n $INTERNAL ]]; then
  for S in `find ../dagger/java/dagger/internal/ -maxdepth 1 -name "*.java" | grep -v -E "$XCL"`; do
    ./fetch internal `basename $S`
  done
else
  for S in `find ../dagger/java/dagger/internal/codegen/ -name "*.java" | grep -v -E "$XCL"`; do
    ./fetch internal `basename $S`
  done
fi
