#!/bin/bash

die () {
    echo "$*"
    exit 1
}

if [[ -z "$1" ]]; then
  die "usage: [internal] pick<JavaClassSimpleName>"
fi

if [[ "internal" == "$1" ]]; then
  INTERNAL=1
  shift
elif [[ "spi" == "$1" ]]; then
  SPI=1
  shift
fi

one="^[[:space:]]*1[[:space:]]*$"
nothing="^[[:space:]]*$"
isjava="^.*[.]java"

for THING in "$@"; do

  if [[ "$THING" =~ $isjava ]]; then
    FILE="${THING}"
  else
    FILE="${THING}.java"
  fi

  if [[ -n $INTERNAL ]]; then
    SOURCE=$(find ../dagger/java/dagger/internal -type f -name $FILE)
    TARGET=$(find compiler/src/main/java/dagger/internal -type f -name $FILE)
  elif [[ -n $SPI ]]; then
    SOURCE=$(find ../dagger/java/dagger/spi -type f -name $FILE)
    TARGET=$(find compiler/src/main/java/dagger/spi -type f -name $FILE)
  else
    SOURCE=$(find ../dagger/java/dagger -type f -name $FILE | fgrep -F -v hilt)
    TARGET=$(find compiler/src/main/java/dagger -type f -name $FILE)
  fi

  if [[ "$SOURCE" =~ $nothing ]] || [[ ! $(echo "$SOURCE" | wc -l) =~ $one ]]; then
    die "Bad source: $SOURCE" "file: $FILE"
  fi

  if [[ "$TARGET" =~ $nothing ]] || [[ ! $(echo "$TARGET" | wc -l) =~ $one ]]; then
    die "Bad target: $TARGET" "file: $FILE"
  fi

  cp "$SOURCE" "$TARGET"
  ./imports "$TARGET"

done
