#!/bin/bash

die () {
    echo "$*"
    exit 1
}

XCL="/producers"
XCL+="|package-info"
XCL+="|/kythe"
XCL+="|/kotlin"
XCL+="|/Producer"
XCL+="|/Produces"
XCL+="|/Production"
XCL+="|/JavacPlugin"
XCL+="|/TypeNames"
XCL+="|/JavacPlugin"
#XCL+="|"

echo $XCL
for S in `find ../dagger/java/dagger/internal/codegen/ -name "*.java" | fgrep -v -e "$XCL"`; do
  ./fetch internal `basename $S`
done

