#!/bin/bash

die () {
    echo "$*"
    exit 1
}

INPUT="$1"
if [[ -z "$INPUT" ]]; then
	die "usage: imports <filename>"
fi


sed -i 's/^import static com.google.auto.common./import static io.jbock.auto.common./g' "$INPUT"
sed -i 's/^import static com.google.common.base./import static dagger.internal.codegen.base./g' "$INPUT"
sed -i 's/^import static androidx.room.compiler.processing.compat.XConverters./import static dagger.internal.codegen.xprocessing.XConverters./g' "$INPUT"
sed -i 's/^import static com.squareup.javapoet./import static io.jbock.javapoet./g' "$INPUT"
sed -i 's/^import androidx.room.compiler.processing./import dagger.internal.codegen.xprocessing./g' "$INPUT"
