#!/bin/bash

die () {
    echo "$*"
    exit 1
}

dit () {
    git --git-dir ../dagger/.git  --work-tree=../dagger "$@"
}

REF_ID=$1
if [[ -z "$REF_ID" ]]; then
  die "usage: pick <ref-id>"
fi

isjava="^.*[.]java"

XCL="/javac/"

dit checkout master
dit pull origin master
dit checkout $REF_ID

for S in `dit show --name-status -- java/dagger/internal/codegen | grep -E ^M | grep -v -E "$XCL" | awk -F 'java/' '{print $2}'`; do
  if [[ "$S" =~ $isjava ]]; then
    cp "../dagger/java/$S" "compiler/src/main/java/$S"
    ./imports "compiler/src/main/java/$S"
  fi
done

