#!/bin/bash

die () {
    echo "$*"
    exit 1
}

REF_ID=$1
if [[ -z "$REF_ID" ]]; then
  die "usage: pick <ref-id>"
fi

isjava="^.*[.]java"

XCL="/javac/"

git --git-dir ../dagger/.git --work-tree=../dagger checkout $REF_ID

for S in `git --git-dir ../dagger/.git --work-tree=../dagger show --name-status -- java/dagger/internal/codegen | grep -E ^M | grep -v -E "$XCL" | awk -F 'java/' '{print $2}'`; do
  if [[ "$S" =~ $isjava ]]; then
    cp "../dagger/java/$S" "compiler/src/main/java/$S"
    ./imports "compiler/src/main/java/$S"
  fi
done

